extends: react-app
plugins:
  - prettier
rules:
  jsx-a11y/anchor-is-valid: off
  import/no-cycle: error
  import/no-extraneous-dependencies:
    - warn
    - devDependencies: false
      optionalDependencies: false
      peerDependencies: true
      bundledDependencies: false
  prettier/prettier: warn
  import/order:
    - warn
    - newlines-between: never
      groups: [builtin, external, internal, parent, sibling, index]
      alphabetize:
        order: asc
      pathGroups:
        - pattern: '@tidb-dashboard/**'
          group: internal
        - pattern: '@core/**'
          group: internal
      pathGroupsExcludedImportTypes:
        - builtin
